coverage:
  range: 70...100
  status:
    patch:
      default:
        target: 80
    project:
      default:
        target: auto
    changes: false
  ignore:
    - "build/*"
    - "deploy/*"
    - "dist/*"
    - "tests/*"
    - "setup.py"
    - "version.py"
comment:
  layout: header, diff, changes, sunburst, uncovered
