version: 2
jobs:
   build:
     docker:
       - image: circleci/python:3.6
     steps:
       - checkout
       - restore_cache:
           key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
       - run: sudo apt-get install -y libgmp3-dev
       - run: sudo pip install coverage codecov
       - run:
           command: |
             python3 -m venv venv
             . venv/bin/activate
       - run: coverage run setup.py test
       - run: codecov
       - save_cache:
           key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
           paths:
             - "venv"

