version: 2
jobs:
   build:
     docker:
       - image: circleci/python:3.5
     steps:
       - checkout
       - run:
           command: |
             python3 -m venv venv
             . venv/bin/activate
       - run: python3 setup.py test
